<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BzSongsSeeder extends Seeder
{
    public function run(): void
    {
        $artistId = DB::table('artists')->where('name', "B'z")->value('id');
        if (!$artistId) {
            $this->command->error("B'z not found in artists table.");
            return;
        }

        $titles = [
            'だからその手を離して',
            'ハートも濡れるナンバー ～stay tonight～',
            'Half Tone Lady',
            'ゆうべのCrying ～This is my truth～',
            'Nothing To Change',
            '孤独にDance in vain',
            "It's not a dream",
            '君を今抱きたい',
            'Fake Lips',
            '君の中で踊りたい',
            'SAFETY LOVE',
            'HURRY UP!',
            'NEVER LET YOU GO',
            'GUITAR KIDS RHAPSODY',
            '夜にふられても',
            'LOVING ALL NIGHT',
            'OH! GIRL',
            'ROSY',
            'OFF THE LOCK',
            'BAD COMMUNICATION',
            'LADY-GO-ROUND',
            'LOVE & CHAIN',
            'B.U.M',
            'BREAK THROUGH',
            'BOYS IN TOWN',
            'GUITARは泣いている',
            'となりでねむらせて',
            'HEY BROTHER',
            '今では…今なら…今も…',
            'SAVE ME!?',
            'STARDUST TRAIN',
            'BE THERE',
            '星降る夜に騒ごう',
            '太陽のKomachi Angel',
            'Good-bye Holy Days',
            'Easy Come, Easy Go!',
            'GO! NUDE! GO!',
            '愛しい人よGood Night...',
            'RISKY',
            'GIMME YOUR LOVE --不屈のLOVE DRIVER-',
            'HOT FASHION -流行過多-',
            'HOLY NIGHTにくちづけを',
            'VAMPIRE WOMAN',
            '確かなものは闇の中',
            'FRIDAY MIDNIGHT BLUE',
            "It's Raining...",
            'LADY NAVIGATION',
            "Pleasure'91 ～人生の快楽～",
            '孤独のRunaway',
            'Mars',
            'ALONE',
            'GO-GO-GIRLS',
            'Wonderful Opportunity',
            'TONIGHT (Is The Night)',
            '『快楽の部屋』',
            '憂いのGYPSY',
            'Crazy Rendezvous',
            'もう一度キスしたかった',
            'WILD LIFE',
            'それでも君には戻れない',
            'あいかわらずなボクら',
            "BLOWIN'",
            'TIME',
            'ZERO',
            '恋心 (KOI-GOKORO)',
            'THE GAMBLER',
            '紅い陽炎',
            'RUN',
            'Out Of Control',
            'NATIVE DANCE',
            'MR. ROLLING THUNDER',
            'さよならなんかは言わせない',
            '月光',
            "Baby, you're my home",
            'Friends',
            'いつかのメリークリスマス',
            '僕の罪',
            'Love is…',
            '恋じゃなくなる日',
            'SEASONS',
            'どうしても君を失いたくない',
            'いつかのメリークリスマス (Reprise)',
            '愛のままにわがままに 僕は君だけを傷つけない',
            'JOY',
            '裸足の女神',
            'KARA･KARA',
            "Don't Leave Me",
            'Mannequin Village',
            'LOVE IS DEAD',
            'おでかけしましょ',
            '未成年',
            '闇の雨',
            'MY SAD LOVE',
            'Queen of Madrid',
            'ヒミツなふたり',
            '赤い河',
            'WILD ROAD',
            "Sweet Lil' Devil",
            'THE BORDER',
            'JAP THE RIPPER',
            'SLAVE TO THE NIGHT',
            '春',
            '破れぬ夢をひきずって',
            'もうかりまっか',
            'farewell song',
            'MOTEL',
            'hole in my heart',
            'ねがい',
            'YOU & I',
            'love me, I love you',
            '東京',
            'LOVE PHANTOM',
            'FUSHIDARA 100%',
            'spirit loose',
            'ザ･ルーズ',
            '夢見が丘',
            '消えない虹',
            '敵がいなけりゃ',
            '砂の花びら',
            'キレイな愛じゃなくても',
            'BIG',
            'drive to MY WORLD',
            'ミエナイチカラ ～INVISIBLE ONE～',
            'MOVE',
            'Real Thing Shakes',
            'Friends II',
            'SNOW',
            '傷心',
            'BABY MOON',
            'sasanqua～冬の陽',
            'ある密かな恋',
            'きみをつれて',
            'FIREBALL',
            '哀しきdreamer',
            'Calling',
            'Liar! Liar!',
            'ビリビリ',
            'DEEP KISS',
            'スイマーよ!!',
            'Survive',
            'ハピネス',
            'Do me',
            '泣いて 泣いて 泣きやんだら',
            'CAT',
            'だったらあげちゃえよ',
            'Shower',
            'さまよえる蒼い弾丸',
            'Hi',
            'HOME',
            'The Wild WInd',
            'ギリギリchop',
            'ONE',
            'F･E･A･R',
            'Brotherhood',
            'ながい愛',
            '夢のような日々',
            '銀の翼で翔べ',
            'その手で触れてごらん',
            '流れゆく日々',
            'SKIN',
            'イカせておくれ！',
            'SHINE',
            '今夜月の見える丘に',
            'あなたならかまわない',
            'May',
            'You pray, I stay',
            'juice',
            'UBU',
            'RING',
            'guilty',
            '[I]',
            'Seventh Heaven',
            '信じるくらいいいだろう',
            '愛のprisoner',
            '煌めく人',
            'Raging River',
            'TOKYO DEVIL',
            'コブシヲニギレ',
            'Thinking of you',
            '扉',
            'Logic',
            'ultra soul',
            'ROCK man',
            'GOLD',
            'まっかなシルク',
            'DEVIL',
            '熱き鼓動の果て',
            '夜よ明けないで',
            '挑めよ儚いこの時に',
            'STAY GREEN ～未熟な旅はとまらない～',
            'Warp',
            'SIGNAL',
            'SURFIN\' 3000GTR',
            'Blue Sunshine',
            '美しき世界',
            'Everlasting',
            'FOREVER MINE',
            'The Spiral',
            'GO★FIGHT★WIN',
            'IT\'S SHOWTIME!!',
            'New Message',
            '野性のENERGY',
            '旅☆EVERYDAY',
            'アラクレ',
            'WAKE UP, RIGHT NOW',
            '儚いダイヤモンド',
            "I'm in love?",
            '愛と憎しみのハジマリ',
            'BIG MACHINE',
            'Nightbird',
            'ブルージーな朝',
            '眩しいサイン',
            'CHANGE THE FUTURE',
            'ROOTS',
            'BANZAI',
            'Magnolia',
            'ARIGATO',
            '輝く運命はその手の中に',
            'もうはなさない',
            '愛のバクダン',
            'Fever',
            '甘く優しい微熱',
            'THE CIRCLE',
            'X',
            'パルス',
            'Fly The Flag',
            'アクアブルー',
            '睡蓮',
            'Sanctuary',
            '白い火花',
            'イカロス',
            'BLACK AND WHITE',
            'Brighter Day',
            'OCEAN',
            'なりふりかまわず抱きしめて',
            'Dear my lovely pain',
            '衝動',
            '結晶',
            'ゆるぎないものひとつ',
            'ピエロ',
            'SPLASH!',
            'MVP',
            'ALL-OUT ATTACK',
            '恋のサマーセッション',
            'ケムリの世界',
            '無言のPromise',
            'MONSTER',
            'Happy Birthday',
            'ネテモサメテモ',
            '雨だれぶるーず',
            '明日また陽が昇るなら',
            '永遠の翼',
            'ロンリースターズ',
            'SUPER LOVE SONG',
            'ここから',
            'FRICTION',
            '純情ACTION',
            '黒い青春',
            '満月よ照らせ',
            'パーフェクトライフ',
            '一心不乱',
            'ONE ON ONE',
            '僕には君がいる',
            'なんという幸せ',
            'わるいゆめ',
            "HOMETOWN BOYS' MARCH",
            '光芒',
            'トラベリンメンのテーマ',
            'オレとオマエの新しい季節',
            'BUDDY',
            'BURN -フメツノフェイス-',
            'yokohama',
            '希望の歌',
            'グローリーデイズ',
            'いつかまたここで',
            'イチブトゼンブ',
            'DIVE',
            'National Holiday',
            'MY LONELY TOWN',
            '綺麗な涙',
            'Introduction',
            'Time FIles',
            'long time no see',
            'PRAY',
            'MAGIC',
            'TINY DROPS',
            'だれにも言えねぇ',
            '夢の中で逢いましょう',
            'Freedom Traim',
            'ひとりじゃないから -Theme Of LIVE-GYM-',
            'さよなら傷だらけの日々よ',
            'Dawn Runner',
            "Don't Wanne Lie",
            'Homebound',
            "C'mon",
            'ひとしずくのアナタ',
            'DAREKA',
            'ボス',
            'Too Young',
            'ピルグリム',
            'ザ・マイスター',
            'デッドエンド',
            '命名',
            'GO FOR IT, BABY -キオクの山脈-',
            '仄かなる火',
            '流星マスク',
            'HEAT',
            '核心',
            'Q&A',
            'ユートピア',
            '有頂天',
            'Endless Summer',
            'Las Vegas',
            'Exit To The Sun',
            'NO EXCUSE',
            'アマリニモ',
            'EPIC DAY',
            'Classmate',
            'Black Coffee',
            '君を気にしない日など',
            'Man Of The Match',
            'RED',
            '世界はあなたの色になる',
            'フキアレナサイ',
            '声明',
            'Still Alive',
            'Dinosaur',
            'CHAMP',
            'ハルカ',
            'それでもやっぱり',
            'Queen Of The Night',
            'SKYROCKET',
            'ルーフトップ',
            '弱い男',
            '愛しき幽霊',
            'King Of The Street',
            'Purple Pink Orange',
            'HINOTORI',
            'マイニューラブ',
            '兵、走る',
            'WOLF',
            'デウス',
            'マジェスティック',
            'MR.ARMOUR',
            'Da La Da Da',
            '恋鴉',
            'Rain & Dream',
            '俺よカルマを生きろ',
            'ゴールデンルーキー',
            'SICK',
            'トワニワカク',
            'きみとなら',
            'UNITE',
            'harunohi',
            'シーズンエンド',
            'ミダレチル',
            'Friends III',
            'Butterfly',
            'こんな時だけあなたが恋しい',
            'GROW & GLOW',
            'SLEEPLESS',
            'Hard Rain Love',
            'COMEBACK -愛しき破片-',
            'YES YES YES',
            'HIghway X',
            'マミレナ',
            '山手通りに風',
            'リヴ',
            'Daydream',
            'You Are My Best',
            'STARS',
            'Dark Rainbow',
            'ペインキラー',
            'イルミネーション',
            '鞭',
            'FMP',
            '恐るるなかれ灰は灰に',
            'The IIIRD Eye',
            'INTO THE BLUE',
            '濁流BOY',
            '片翼の風景',
            'FAITH?',
            'その先へ',
            'Heaven Knows',
            '完全無欠',
        ];

        $now = now();
        $rows = array_map(fn($title) => [
            'artist_id'  => $artistId,
            'title'      => $title,
            'created_at' => $now,
            'updated_at' => $now,
        ], $titles);

        // 既存タイトルはスキップ
        $existing = DB::table('songs')
            ->where('artist_id', $artistId)
            ->pluck('title')
            ->flip();

        $insert = array_filter($rows, fn($r) => !isset($existing[$r['title']]));

        if (empty($insert)) {
            $this->command->info('All B\'z songs already exist.');
            return;
        }

        foreach (array_chunk($insert, 100) as $chunk) {
            DB::table('songs')->insert($chunk);
        }

        $this->command->info('Inserted ' . count($insert) . " B'z songs.");
    }
}
